=== DIAGNijmegen/rse-grand-challenge-dicom-de-id-procedure/schemas/procedure.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/sop-class-schema",
    "type": "object",
    "required": [
        "version",
        "default",
        "dicomStandardVersion",
        "justification",
        "sopClass"
    ],
    "properties": {
        "version": {
            "type": "string",
            "pattern": "^\\d{4}\\.([1-9]|1[0-2])\\.\\d+$"
        },
        "default": {
            "$ref": "#/$defs/defaultEnum"
        },
        "dicomStandardVersion": {
            "type": "string",
            "minLength": 1
        },
        "justification": {
            "type": "string",
            "minLength": 1
        },
        "sopClass": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "default",
                    "justification",
                    "tag"
                ],
                "properties": {
                    "default": {
                        "$ref": "#/$defs/defaultEnum"
                    },
                    "justification": {
                        "type": "string",
                        "minLength": 1
                    },
                    "tag": {
                        "type": "object",
                        "propertyNames": {
                            "pattern": "\\([0-9A-FX]{4},[0-9A-FX]{4}\\)"
                        },
                        "additionalProperties": {
                            "type": "object",
                            "required": [
                                "default",
                                "justification"
                            ],
                            "properties": {
                                "default": {
                                    "$ref": "#/$defs/defaultEnum"
                                },
                                "justification": {
                                    "type": "string",
                                    "minLength": 1
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false,
    "$defs": {
        "defaultEnum": {
            "type": "string",
            "enum": [
                "X",
                "K",
                "D",
                "Z",
                "U",
                "R"
            ]
        }
    }
}

=== DIAGNijmegen/rse-grand-challenge-dicom-de-id-procedure/dist/procedure.json
{
  "default": "R",
  "dicomStandardVersion": "2025b",
  "justification": "Unsupported SOP Class",
  "sopClass": {
    "1.2.840.10008.5.1.4.1.1.2": {
      "default": "X",
      "justification": "Unsupported data element",
      "tag": {
        "(0008,0005)": {
          "default": "K",
          "justification": "Required if an expanded or replacement character set is used"
        },
        "(0008,0008)": {
          "default": "K",
          "justification": "Generally required"
        },
        "(0008,0012)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0013)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0014)": {
          "default": "U",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0015)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0016)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0017)": {
          "default": "U",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0018)": {
          "default": "U",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,001A)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,001B)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,001C)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0020)": {
          "default": "Z",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0021)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0022)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0023)": {
          "default": "X",
          "justification": "Grand-challenge binds together series as a single value"
        },
        "(0008,002A)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0030)": {
          "default": "Z",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0031)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0032)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0033)": {
          "default": "X",
          "justification": "Grand-challenge binds together series as a single value"
        },
        "(0008,0050)": {
          "default": "Z",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0051)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0053)": {
          "default": "D",
          "justification": "Required if special operation has ever occured to the data."
        },
        "(0008,0054)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0060)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0070)": {
          "default": "K",
          "justification": "Required, manufacturer might be relevant"
        },
        "(0008,0080)": {
          "default": "D",
          "justification": "Required, under some condition"
        },
        "(0008,0081)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0082)": {
          "default": "D",
          "justification": "Required, under some condition"
        },
        "(0008,0090)": {
          "default": "Z",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0096)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,009C)": {
          "default": "Z",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,009D)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0100)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0102)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0103)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0104)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0105)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0106)": {
          "default": "D",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0107)": {
          "default": "D",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0109)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,010A)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,010B)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,010C)": {
          "default": "K",
          "justification": "If present, it is required"
        },
        "(0008,010D)": {
          "default": "D",
          "justification": "Identifies a person or context group, sometimes required"
        },
        "(0008,010E)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,010F)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0110)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0112)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0114)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0115)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0116)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0117)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0118)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0119)": {
          "default": "K",
          "justification": "Required, parent sequence should be targeted for actions"
        },
        "(0008,0120)": {
          "default": "U",
          "justification": "Universal ID: could be traced to all kinds of institutes or entities"
        },
        "(0008,0121)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0122)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0123)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0124)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0201)": {
          "default": "X",
          "justification": "[AUTO] Basic Profile"
        },
        "(0008,0300)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0301)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0302)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0303)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0304)": {
          "default": "K",
          "justification": "If present, it is required"
        },
        "(0008,0305)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0306)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0307)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0308)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0309)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,030A)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,030B)": {
          "default": "K",
          "justification": "If present, it is required"
        },
        "(0008,030C)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,030D)": {
          "default": "K",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,030E)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,030F)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,0310)": {
          "default": "X",
          "justification": "[AUTO] Attribute-Module type"
        },
        "(0008,1010)": {
          "default": "X",
